---
deployment:
  tasks:
    - export DEPLOYPATH=/home/leaf3471/public_html/
    - /bin/rsync -a --exclude='config/database.php' --exclude='config/config.php' application/ $DEPLOYPATH/application/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
